### ISSUE TITLE
Add support for handling *n* number of connections per input for nodes during expression creation

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/gantz#17]
## Current Behaviour

Currently, gantz expects one connection per input on each node. If there are no connections to an input, gantz will call `Default::default()`. In the case that there are more than one input, it uses the first discovered input when walking the incoming directed neighbours of the node. The current setup is very limiting and may cause unexpected behaviour in a lot of situations.

## Possible Better Alternatives

Instead, we should allow nodes themselves to decide what kind of input configurations they support. E.g. it may be useful for a `print` node to support many connections to its input, as the behaviour is quite unambiguous and could be quite useful. An `add` node on the other hand should not support any more than one connection at a time to its left and right inputs, as the behaviour in these cases is not clear.

In order to support this, it might be best for the `Node::expr` argument to take a `Vec<Vec<syn::Expr>>` so that the node can decide how to handle the given configuration of inputs.

In order to get some feedback from the node on whether or not a configuration is valid, a couple of options come to mind.

### 1. Returning A Result from `Node::expr`

Rather than returning an `Expr` directly from the `fn expr` method, return some sort of result type indicating whether or not a valid expression can be generated for the given input connection configuration.

### 2. Add a `Node::valid_input_configs` method

Add a separate method to the node trait along the lines of `Node::valid_input_configs` which can be used by gantz to check graph validity before it even begins attempting to generate any code. The method signature might look something like this:
```rust
fn valid_input_configs(&self) -> Vec<Vec<InputConf>>;
```
where the result is a list where each item is a description of a valid number of connections for each input. E.g. an add node impl might look something like this:
```rust
fn valid_input_configs(&self) -> Vec<Vec<InputConf>> {
    vec![
      vec![InputConf::N(1), InputConf::N(1)],
      vec![InputConf::N(1), InputConf::N(0)],
    ]
}
```
whereas a `print` implementation might look like this:
```rust
fn valid_input_configs(&self) -> Vec<Vec<InputConf>> {
    vec![
        vec![InputConf::Any],
    ]
}
```
The `InputConf` type might look something like this:
```rust
pub enum InputConf {
    /// A specific number of inputs.
    N(u32),
    /// A range of inputs,
    Range(std::ops::Range<u32>),
    /// Any number of inputs.
    Any,
```
This approach has the benefit being of being able to query valid input configurations separately from the code generation process, which might help for quicker GUI feedback and allow for doing interesting things like graph generation.

cc @freesig just thought I'd start an issue and get some thoughts down on this multiple-connection-per-input stuff before I go on and start this temporary project stuff. Feel free to run with this in your own direction though if you're still keen!

**Comment by freesig** [comment]
I'm just having a think about this issue and is there actually any other use cases for a node that takes more then one output into the same input other then print?

I'm thinking that if you are taking multiple outputs into an input then you are probably combining them in some way like:
![image](https://user-images.githubusercontent.com/7286454/55047007-62d63500-5097-11e9-9386-7c9a9c947dae.png)

In fact we could handle print like this as well like:
![image](https://user-images.githubusercontent.com/7286454/55047081-a29d1c80-5097-11e9-898e-72db9b998154.png)

This could even happen internally with the codegen. So when the user puts multiple outputs into a print we generate concats in the order they are added or something

**Comment by mitchmindtree** [comment]
True, this is a really good point, I'm actually really struggling to think of a case other than print/debug style things where it would actually be useful!

The concat idea definitely makes sense, especially when we could also provide `tuple` nodes and `vec!` nodes that make combination a bit easier. It also makes it clearer in how print should actually behave when this case  happens - otherwise it's kind of ambiguous, i.e. will it print in a big list? or print one input at a time?

I'm happy to say case closed for the more-than-one-connection-per-input side of things for now if you are? It definitely keeps things much simpler. I'll close this for now and open another issue specifically for how to deal with nodes either having 1 or 0 connections on an input.
