### ISSUE TITLE
extern 2018

### ISSUE THREAD

**Issue by freesig** [nannou-org/gantz#26]
Just a small issue but we should probably stop using `extern some_crate` in favor of `use some_crate` this is crate is marked 2018

**Comment by mitchmindtree** [comment]
I think the only case in which this crate uses extern crate atm is when `#[macro_use]` is needed - I think I was getting errors saying that the macro wasn't available otherwise?

**Comment by freesig** [comment]
I think that `#[macro_use]` is no longer needed in 2018 and instead `use some_crate::some_macro` [reference](https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html)

**Comment by mitchmindtree** [comment]
@freesig nice just saw this in #28. Closing now as #28 is merged.
