### ISSUE TITLE
Availability of Types for Node inputs and outputs

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/gantz#27]
Currently gantz represents nodes as some number of inputs with unknown types and an expression that processes these inputs and returns some number of outputs, also with unknown types.

## Upsides of Unknown Input and Output Types

The reason we can get away with not having to know the types is because code generation for a graph node simply generates a large number of statements that get placed in the body of a function. We then rely on the rust compiler to infer types for the entire body of the function.

One benefit of this is that it makes the `Node` trait quite trivial to implement. The `Expr` node is a good example of this:

```rust
let add = node::expr("#l + #r").unwrap();
```

We don't have to worry about the types of the inputs and outputs (or in this case, the add node's generic input types constrained by the `Add` trait, and output associated type). Instead, Rust infers all of this during compilation meaning we still get rust type safety in our node graphs even though we never had to specify any types.

## Downsides

Some issues that come to mind:

- We cannot generate functions for the evaluation of individual nodes or their branches (see #21) if we don't know the types to use in the signature. Being able to do so would allow us to generate more modular code (rather than one giant block of statements per graph) that might assist with incremental compilation and in turn improve responsiveness of gantz itself in downstream GUI applications.
- We cannot know whether a connection between the output of one node and the input of another is valid until rustc has type-checked the function. This will likely make it slightly tricky to associate type-related compile errors with certain nodes - we'll have to trace line/col numbers back through generated code to find the node being referenced.
- It is unclear how we will handle nesting and composing together different graph nodes while also generating a unique crate for each graph node. If we are to generate a unique crate per node, we also need to generate a function that will allow for evaluating that graph if it is used as a node within another graph. To do this, we would need to know the types of the graph's  inlets and outlets.

## Options moving forward

- **Stick with not knowing any types** - We'd have to inline *everything* (including nested graph nodes) and hope that incremental compilation of individual statements is pretty good.
- **Optionally typed inputs and outputs** - We could allow nodes to opt-in to specifying types for their inputs and outputs. This would allow us to generate functions with type signatures, as long as all inputs to that function and the result of the function are known. We could ensure that graph `Inlet` and `Outlet` nodes *do* always have types specified to allow for the generation of individual crates per graph node.
- **Enforce specifying types always** - We would be able to generate much more compiler-friendly code, but would have to solve many other problems, like how to generate functions with generic inputs or outputs, how to change the `Node` API to ensure this and allow for generics constrained by traits, and how to maintain an ergonomic API for users in general.

cc @freesig

**Comment by freesig** [comment]
I think there is one more option to consider.
_I'm not sure if this is possible or feasible but definitely worth considering_

The idea is to use a stack system and track who push's pop's memory at codegen time. It could be done by keeping a Vec<syn::Expr> which hold which types are on the stack during the codegen.
These types could be obtained from asking the nodes what type they need to store.

__[A rough idea of what I mean](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2cf526b74b21fd9d839d0f329958c0c8)__
I don't have the macro skills to make a complete working example but I hope this can convey the idea.

__Caveats:__
- Obviously this is really unsafe however this code will be generated and never written by hand. So my assumption is during the generation process we can actually guarantee correctness.
- The above code could still be optimized a lot and I think the slowest part should just be copying the data on and off the stack. But this would be the same cost you would need when copying things into `Box<Any>`
- The bug question is: is this even worth it as maybe `Box<Any>` with downcasting is never a bottleneck, however if I've assumed correctly this idea should be as fast as possible because all the checks happen at codegen time not runtime like with `Box<Any>`.

**Comment by mitchmindtree** [comment]
## Optionally Typed Inputs & Outputs

I'm leaning towards this approach as it seems to allow us access to the best of having both unknown and known types.

The primary benefit of knowing the types of inputs and outputs (and the key that solves the 3 main downsides mentioned in the OP) is the ability to generate a complete function. With rust's functions we achieve modularity and a clearly typed boundary. This leads me to think that, if we are to go the optionally typed route, it is probably only worth providing the option to specify either _all_ types (i.e. the entire function signature) or *no* types at all (an expression, as is currently the case). That is, there is probably no point in allowing a node implementation to specify only the output type, or only the type for one of its inputs as we are still unable to generate a function for the type and in turn don't gain any immediate benefits from the extra information.

### API

Perhaps we could change the existing `expr` method to a method that allows for returning either an expression *or* a function, perhaps as variants of some sort of `Evaluator` enum? E.g.

```rust
pub trait Node {
    // ...
    fn eval(&self) -> Evaluator;
    // ...
}

pub enum Evaluator {
    Expr {
        expr: Box<Fn(Vec<syn::Expr>) -> syn::Expr>,
        n_inputs: u32,
        n_outputs: u32,
    },
    Fn(syn::FnDecl),
}
```

In this case, the returned evaluator would need also need to provide a method for producing the actual expression that will be used to evaluate the node. In the case of the function, this would be a call to that function. In the case of the `Expr`, this would be provided via the `expr` field.

There are still a few questions to be answered:

- How does this tie in with conditional evaluation? Can a node with typed inputs and outputs do conditional evaluation? This will be important to consider if we want to allow users to create graphs that have conditionally evaluated outlets. Related to #21.
- How do we feed state into functions? Perhaps we can implicitly add a final argument to the produced `syn::FnDecl`s allowing us to feed the necessary node state down the call stack? Related to #19.
