### ISSUE TITLE
Nodes as dynamic/shared libraries

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/gantz#3]
@robclouth aka bobbyC mentioned this could be a sweet approach that allows for both compiling individual nodes into fairly efficient representations and composing them together at runtime. Just leaving this here so I remember to look into it!

Related links:

- [libloading](https://github.com/nagisa/rust_libloading) for loading dynamic/shared libraries at runtime and using functions/statics that they contain.

**Comment by robclouth** [comment]
Ace
